baseURL = "https://zemzemzen.com/"
title = "ZemZem Blog"
theme = "PaperMod"
languageCode = "en-us"

[pagination]
  pagerSize = 8

[params]
  ShowBreadCrumbs = true
  ShowReadingTime = true
  ShowShareButtons = true
  defaultTheme = "auto"         # light / dark mode toggle
  featureSections = ["posts"]   # show recent posts on homepage
  fuse = true                   # enable built-in search

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Substances"
    url = "/substances/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

