baseURL = 'https://zemzemzen.com/'
languageCode = 'en-us'
title = 'ZemzemzenBlog'
theme = 'PaperMod'

[params]
	ShowReadingTime = true
	ShowShareButtons = true
	homeInfoParams = { Title = "ZemZem Blog", Content = "Exploring kanna, kratom, kava, and natural states of mind." }
	
